/** @type {import('tailwindcss').Config} */
// Sistema de diseño "The Academic Atelier" (ver stitch-export/EspecificacionesDiseño.md)
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        background: '#f8f9fa',
        surface: '#f8f9fa',
        'surface-bright': '#f8f9fa',
        'surface-dim': '#d1dce0',
        'surface-variant': '#dbe4e7',
        'surface-tint': '#255dad',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f1f4f6',
        'surface-container': '#eaeff1',
        'surface-container-high': '#e3e9ec',
        'surface-container-highest': '#dbe4e7',
        primary: '#255dad',
        'primary-dim': '#1151a0',
        'primary-container': '#d7e2ff',
        'primary-fixed': '#d7e2ff',
        'primary-fixed-dim': '#c1d5ff',
        'on-primary': '#f7f7ff',
        'on-primary-container': '#0f509f',
        'on-primary-fixed': '#003e81',
        'on-primary-fixed-variant': '#215aaa',
        'inverse-primary': '#73a3f8',
        secondary: '#5d5f65',
        'secondary-dim': '#515359',
        'secondary-container': '#e2e2e9',
        'secondary-fixed': '#e2e2e9',
        'secondary-fixed-dim': '#d4d4db',
        'on-secondary': '#f9f8ff',
        'on-secondary-container': '#505157',
        'on-secondary-fixed': '#3d3f45',
        'on-secondary-fixed-variant': '#5a5b61',
        tertiary: '#5e5c78',
        'tertiary-dim': '#52506b',
        'tertiary-container': '#d5d1f2',
        'tertiary-fixed': '#d5d1f2',
        'tertiary-fixed-dim': '#c7c3e3',
        'on-tertiary': '#fcf7ff',
        'on-tertiary-container': '#484661',
        'on-tertiary-fixed': '#35334d',
        'on-tertiary-fixed-variant': '#52506b',
        error: '#9f403d',
        'error-dim': '#4e0309',
        'error-container': '#fe8983',
        'on-error': '#fff7f6',
        'on-error-container': '#752121',
        background: '#f8f9fa',
        'on-background': '#2b3437',
        'on-surface': '#2b3437',
        'on-surface-variant': '#586064',
        outline: '#737c7f',
        'outline-variant': '#abb3b7',
        'inverse-surface': '#0c0f10',
        'inverse-on-surface': '#9b9d9e',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        display: ['Manrope', 'sans-serif'],
        body: ['Public Sans', 'sans-serif'],
        label: ['Public Sans', 'sans-serif'],
      },
      // Escala tipográfica Material 3 usada por las pantallas Stitch
      fontSize: {
        'display-lg': ['3.5rem', { lineHeight: '4rem' }],
        'display-md': ['2.8rem', { lineHeight: '3.25rem' }],
        'display-sm': ['2.25rem', { lineHeight: '2.75rem' }],
        'headline-lg': ['2rem', { lineHeight: '2.5rem' }],
        'headline-md': ['1.75rem', { lineHeight: '2.25rem' }],
        'headline-sm': ['1.5rem', { lineHeight: '2rem' }],
        'title-lg': ['1.375rem', { lineHeight: '1.75rem' }],
        'title-md': ['1rem', { lineHeight: '1.5rem' }],
        'title-sm': ['0.875rem', { lineHeight: '1.25rem' }],
        'body-lg': ['1rem', { lineHeight: '1.5rem' }],
        'body-md': ['0.875rem', { lineHeight: '1.25rem' }],
        'body-sm': ['0.75rem', { lineHeight: '1rem' }],
        'label-lg': ['0.875rem', { lineHeight: '1.25rem' }],
        'label-md': ['0.75rem', { lineHeight: '1rem' }],
        'label-sm': ['0.6875rem', { lineHeight: '1rem' }],
      },
    },
  },
  plugins: [],
}
